[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\x32\x66ile:///home/tienduc/Downloads/video/bad_apple.mp4)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\x16\0\0\x5U\0\0\x2\xeb\0\0\x2\xaf\0\0\0$\0\0\x5L\0\0\x2\xfc\0\0\0\0\x2\0\0\0\x5V\0\0\0\x1\0\0\0\x16\0\0\x5T\0\0\x2\xea)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(1364 626)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[OpenDialog]
advanced=false
size=@Size(526 423)

[Plugins]
Header-State=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2p\0\0\0\x3\0\x1\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x3\0\0\0\xc8\0\0\0\x1\0\0\0\0\0\0\0o\0\0\0\x1\0\0\0\0\0\0\x1\x39\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\0\0\0\x64)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x1\x9d\0\0\0\xb8\0\0\x3\xb8\0\0\x2G\0\0\x1\x9d\0\0\0\xb8\0\0\x3\xb8\0\0\x2G\xff\xff\xff\xff\0\0\0\0\x5V\0\0\x1\x9d\0\0\0\xb8\0\0\x3\xb8\0\0\x2G)

[PluginsDialog]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x4\x2\0\0\0\b\0\0\x5M\0\0\x2\xe2\0\0\x4\x3\0\0\0\t\0\0\x5L\0\0\x2\xe1\0\0\0\0\0\0\0\0\x5V\0\0\x4\x3\0\0\0\t\0\0\x5L\0\0\x2\xe1)

[Preferences]
geometry="@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x1\x1c\0\0\0#\0\0\x4=\0\0\x2\xe0\0\0\x1\x1d\0\0\0$\0\0\x4<\0\0\x2\xdf\0\0\0\0\0\0\0\0\x5V\0\0\x1\x1d\0\0\0$\0\0\x4<\0\0\x2\xdf)"

[RecentsMRL]
list=file:///run/media/ngkbthg/Tien%20Duc/%E1%BA%A3nh-video/video/bg.webm, file:///run/media/ngkbthg/Tien%20Duc/%E1%BA%A3nh-video/video/bg.mp4, file:///run/media/ngkbthg/Tien%20Duc/%E1%BA%A3nh-video/video/AQN2zkK6w-h9V_l8lvXZ4HovDV8Y7EFKLbMi6XTLcpQAIYL7OBHHvdFWPIUC7RnYekPP3TCT-56qHbur0qGiiwVJ.mp4, file:///home/tienduc/fb.mp4, file:///home/tienduc/downloads/video/wallneko.mp4, file:///home/tienduc/test.mp4, file:///home/tienduc/2025-08-14%2012-10-28.mp4, file:///home/tienduc/2025-08-14%2011-54-50.mkv, file:///home/tienduc/downloads/video/bad_apple.mp4, file:///home/tienduc/2025-08-06%2015-11-51.mkv, file:///run/media/tienduc/ngkbthg/stuff/WIN10.PRO.AIO.U28.X64.%28WPE%29.ISO, file:///home/tienduc/downloads/temp/AQMnLgO1VXywJtMJSYhGjxjBNpVQFVDqEILKtDqrgOv775_2n5ZPTngO5qTYdE5mIaCfpBrY5gF01RQ9PaIwRWj1OXQutbcVGnmg3bg.mp4, file:///run/media/tienduc/1234-5678/bg.mpv, file:///run/media/tienduc/1234-5678/bg.mp4, file:///home/tienduc/Downloads/video/bad_apple.mp4, file:///home/tienduc/Downloads/video/badapple.mp4, file:///home/tienduc/Downloads/video/m2-res_854p.mp4
times=0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
